;METADATA=(Diff=true, UseCommands=true) Обязательное добовление значения для успешного запуска файлов игры.
[/Script/Engine.GameSession]
MaxPlayers=85 Количествво игроков на сервере.

[/Script/TheIsle.TIGameSession]
ServerName=Название сервера.
MapName=Gateway Название карты.
MaxPlayerCount=85 Количествво игроков на сервере.
bEnableHumans=false Люди выключены (не советую ставить включенным, на сегодня они не ктуальны в игре, до полного релиза выхода людей с настроенными механиками.)
bQueueEnabled=true Включить очередь на сервере, если он переполнен.
QueuePort= Указать порт очереди, если собираетесь использовать RCON.
bServerPassword=false Установить пароль на сервере, если он вам требуется.
ServerPassword= Номер пароля.
bRconEnabled=true Включить RCON.
RconPassword= Пароль для RCON (кроме вас, никто не должен его знать!)
RconPort= Номер порта RCON.
QueryPort= Указать порт запроса для RCON.
bServerDynamicWeather=false Динамическую погоду сервера выключить.
ServerDayLengthMinutes=60 Установить время дня в минутах.
ServerNightLengthMinutes=50 Установить время ночи в минутах.
bServerWhitelist=false Включить или выключить белый список.
bEnableGlobalChat=true Включить глобальный чат.
bSpawnPlants=true Спавн растений включен.
bSpawnAI=true Спавн ИИ включен.
AISpawnInterval=5 Интервал спавна ИИ, чем выше значение, тем больше спавн.
bEnableMigration=true Включить миграцию.
bServerMutations=true Включить мутации на сервере. (Не добавляйте список мутаций в игру. Если это сделать ваша производительность сервера в разы упадёт).
MaxMigrationTime=5400 Максимальное время миграции указать в секундах.
GrowthMultiplier=2 Скорость роста. Стандартное значение 1. Если у вас направление полу реализм или реализм лучше использовать скорость роста 2. Для кос серверов от 5 до 10. 
ServerDeadBodyTime=5400 Время смерти сервера, указать в секундах. (Честно не совсем понятная для меня команда, но так же не обходимая для сервера).
bEnabledMutations=true Включенные мутации (если добавить эту конфигурации, она даст игрокам ставить любые мутации из игры, да же скрытные).
bUseRegionSpawning=true Спавн в регионе включить. (Не ставьте настроенные точки спавна, данная механика была нарушена разработчиками игры и меню выбора точки спавна не даст вам выбрать направление, в следствии чего вы просто залагаете и не сможите нчиего сделать).
LocalChatRange=20000.f Диапазон видимости локального чата.
bAllowReplay=true Включить запись реплеев на сервере.
bServerStability=True Помогает избежать повреждения файлов сохранения.

Установить список лимитов на сервере. Ставите как вам удобно.
SpeciesLimits=(SpeciesName="Hypsilophodon",Limit= )
SpeciesLimits=(SpeciesName="Pachycephalosaurus",Limit= )
SpeciesLimits=(SpeciesName="Stegosaurus",Limit= )
SpeciesLimits=(SpeciesName="Tenontosaurus",Limit= )
SpeciesLimits=(SpeciesName="Carnotaurus",Limit= )
SpeciesLimits=(SpeciesName="Ceratosaurus",Limit= )
SpeciesLimits=(SpeciesName="Deinosuchus",Limit= )
SpeciesLimits=(SpeciesName="Diabloceratops",Limit= )
SpeciesLimits=(SpeciesName="Dryosaurus",Limit= )
SpeciesLimits=(SpeciesName="Omniraptor",Limit= )
SpeciesLimits=(SpeciesName="Pteranodon",Limit= )
SpeciesLimits=(SpeciesName="Troodon",Limit= )
SpeciesLimits=(SpeciesName="Beipiaosaurus",Limit= )
SpeciesLimits=(SpeciesName="Gallimimus",Limit= )
SpeciesLimits=(SpeciesName="Dilophosaurus",Limit= )
SpeciesLimits=(SpeciesName="Herrerasaurus",Limit= )
SpeciesLimits=(SpeciesName="Tyrannosaurus",Limit= )
SpeciesLimits=(SpeciesName="Allosaurus",Limit= )
SpeciesLimits=(SpeciesName="Triceratops",Limit= )

[/Script/TheIsle.TIGameStateBase]
AdminsSteamIDs= Steam ID администратора.
WhitelistIDs= Steam ID VIP пользователя. Позволяет войти на сервер вне очереди.

Список всех видов динозавров. На ваше усмотрение кого добавлять или нет. Если не хотите, просто удалите из списка.
AllowedClasses=Hypsilophodon
AllowedClasses=Pachycephalosaurus
AllowedClasses=Stegosaurus
AllowedClasses=Tenontosaurus
AllowedClasses=Carnotaurus
AllowedClasses=Ceratosaurus
AllowedClasses=Deinosuchus
AllowedClasses=Diabloceratops
AllowedClasses=Dryosaurus
AllowedClasses=Omniraptor
AllowedClasses=Pteranodon
AllowedClasses=Troodon
AllowedClasses=Beipiaosaurus
AllowedClasses=Gallimimus
AllowedClasses=Dilophosaurus
AllowedClasses=Herrerasaurus
AllowedClasses=Maiasaura
AllowedClasses=Triceratops
AllowedClasses=Allosaurus
AllowedClasses=Tyrannosaurus

Список ботов, которые будут спавниться у вас на сервере.
DisallowedAIClasses=Compsognathus
DisallowedAIClasses=Pterodactylus
DisallowedAIClasses=Boar
DisallowedAIClasses=Deer
DisallowedAIClasses=Goat
DisallowedAIClasses=Seaturtle
