;METADATA=(Diff=true, UseCommands=true)
[/Script/Engine.GameSession]
MaxPlayers=85

[/Script/TheIsle.TIGameSession]
ServerName=
MapName=Gateway
MaxPlayerCount=85
bEnableHumans=false
bQueueEnabled=true
QueuePort=
bServerPassword=false
ServerPassword=
bRconEnabled=true
RconPassword=
RconPort=
QueryPort=
bServerDynamicWeather=false
ServerDayLengthMinutes=60
ServerNightLengthMinutes=50
bServerWhitelist=false
bEnableGlobalChat=true
bSpawnPlants=true
bSpawnAI=true
AISpawnInterval=5
bEnableMigration=true
bServerMutations=true
MaxMigrationTime=5400
GrowthMultiplier=2
ServerDeadBodyTime=5400
bEnabledMutations=true
bUseRegionSpawning=true
LocalChatRange=20000.f
bAllowReplay=true
SpeciesLimits=(SpeciesName="Hypsilophodon",Limit=10)
SpeciesLimits=(SpeciesName="Pachycephalosaurus",Limit=8)
SpeciesLimits=(SpeciesName="Stegosaurus",Limit=5)
SpeciesLimits=(SpeciesName="Tenontosaurus",Limit=8)
SpeciesLimits=(SpeciesName="Carnotaurus",Limit=3)
SpeciesLimits=(SpeciesName="Ceratosaurus",Limit=5)
SpeciesLimits=(SpeciesName="Deinosuchus",Limit=2)
SpeciesLimits=(SpeciesName="Diabloceratops",Limit=6)
SpeciesLimits=(SpeciesName="Omniraptor",Limit=8)
SpeciesLimits=(SpeciesName="Pteranodon",Limit=6)
SpeciesLimits=(SpeciesName="Troodon",Limit=10)
SpeciesLimits=(SpeciesName="Beipiaosaurus",Limit=10)
SpeciesLimits=(SpeciesName="Gallimimus",Limit=10)
SpeciesLimits=(SpeciesName="Dilophosaurus",Limit=4)
SpeciesLimits=(SpeciesName="Herrerasaurus",Limit=10)
SpeciesLimits=(SpeciesName="Tyrannosaurus",Limit=2)
SpeciesLimits=(SpeciesName="Allosaurus",Limit=3)
SpeciesLimits=(SpeciesName="Triceratops",Limit=4)

[/Script/TheIsle.TIGameStateBase]
AdminsSteamIDs=76561198325795178
WhitelistIDs=
AllowedClasses=Hypsilophodon
AllowedClasses=Pachycephalosaurus
AllowedClasses=Stegosaurus
AllowedClasses=Tenontosaurus
AllowedClasses=Carnotaurus
AllowedClasses=Ceratosaurus
AllowedClasses=Deinosuchus
AllowedClasses=Diabloceratops
AllowedClasses=Omniraptor
AllowedClasses=Pteranodon
AllowedClasses=Troodon
AllowedClasses=Beipiaosaurus
AllowedClasses=Gallimimus
AllowedClasses=Dilophosaurus
AllowedClasses=Herrerasaurus
AllowedClasses=Maiasaura
AllowedClasses=Triceratops
AllowedClasses=Allosaurus
AllowedClasses=Tyrannosaurus

DisallowedAIClasses=Compsognathus
DisallowedAIClasses=Pterodactylus
DisallowedAIClasses=Boar
DisallowedAIClasses=Deer
DisallowedAIClasses=Goat
DisallowedAIClasses=Seaturtle